### ISSUE TITLE
Analyze command should overwrite existing extracted template instead of using stale contents

### ISSUE THREAD

**Issue by Eilon** [sayedihashimi/dotnet-new-web#37]
After the `analyze` command detected some missing metadata in my template NUPKG, I made fixes to my metadata, and ran the analyzer again, only to find that the same error was reported!

It turns out the analyzer doesn't overwrite files when it extracts the ZIP, so it keep analyzing old template contents. My local builds produce the same exact filename/version while I'm working on local changes, so the analyzer will always see stale contents after the first run.

Repro steps:

1. Create a template NUPKG with bad/missing metadata
1. Run `templates analyze -p c:\path\to\templates.nupkg`
1. See metadata warning/error
1. Fix the metadata, rebuild the template to the _exact same_ filename
1. Run analyzer again

Expected: See errors GONE because they should be fixed now

Actual: Errors are still shown.

The problem seems to be here:

https://github.com/sayedihashimi/dotnet-new-web/blob/e201d9ff619e5aaff6b010033facfdef30134a30/src/TemplatesShared/RemoteFile.cs#L92-L98

I'm not sure if it's correct to make this _always_ overwrite because that might not be right for other uses of this API. But I think for the analyzer it should overwrite by default. You could always add "fancier" logic later to detect cases where it's truly safe, such as looking at timestamps.

**Comment by sayedihashimi** [comment]
Thanks, I will take a look. For analyzer scenarios, I think I'll just add a flag to always extract and pass that in.

**Comment by Eilon** [comment]
Yeah that is probably the best/safest option.

**Comment by sayedihashimi** [comment]
@Eilon the fix has been published in version [`1.0.3`](https://www.nuget.org/packages/sayedha.template.command/1.0.3). The release has some other bug fixes, so please let me know if you run into any issues.
